var CONSTANTS = {
  SELECTED_MENU_WORD: "SELECTED_MENU_WORD",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  SHOW_MARK: "SHOW_MARK",
  ADD_WORD: "ADD_WORD",
  REMOVE_WORD: "REMOVE_WORD",
};

var ROLE = {
  ADMIN: "Admin",
  WAREHOUSE: "Warehouse",
  SHIPPER: "Shipper",
};

var TOASTIFY = {
  SUCCESS: "success",
  ERROR: "error",
  WARNING: "warning",
  INFO: "info",
};

var CONST_PRACTICE_WORD = {
  SELECTED_MENU_WORD: "SELECTED_MENU_WORD",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  SHOW_MARK: "SHOW_MARK",
  ADD_WORD: "ADD_WORD",
  REMOVE_WORD: "REMOVE_WORD",
};

export { ROLE, TOASTIFY, CONST_PRACTICE_WORD };
export default CONSTANTS;
