import { date } from "zod";
import { PracticeIcon } from "../based/icon/configIcon";

const DataCard = [
  {
    id: 1,
    title: "Tổng số từ vựng",
    description: "Tổng số từ vựng của bạn",
    total: 100,
    color: "bg-totalWord",
    cursor: "pointer",
    icon: <PracticeIcon.WordSuccess />,
  },
  {
    id: 2,
    title: "Tổng số từ đã biết",
    description: "Tổng số từ vựng bạn đã biết",
    total: 80,
    color: "bg-totalWordKnow",
    cursor: "pointer",
    icon: <PracticeIcon.WordSuccess />,
  },
  {
    id: 3,
    title: "Tổng số từ đã nhớ",
    description: "Tổng số từ vựng đã nhớ, cần ôn tập lại",
    total: 20,
    color: "bg-totalWordRemember",
    cursor: "pointer",
    icon: <PracticeIcon.WordSuccess />,
  },
  {
    id: 4,
    title: "Số điểm đạt được",
    description: "Số điểm bạn đạt được",
    total: 80,
    color: "bg-totalPoint ",
    cursor: "default",
    icon: <PracticeIcon.WordSuccess />,
  },
];

const DataSelect = [
  {
    id: 1,
    title: "Ôn tập từ vựng",
    description: "Ôn tập lại các từ vựng của bạn",
    img: "https://friendlystock.com/wp-content/uploads/2019/09/6-brain-learning-cartoon-clipart.jpg",
    link: "/practice/word",
  },
  {
    id: 2,
    title: "Ôn tập ngữ pháp",
    description: "Ôn tập lại các ngữ pháp đã học",
    img: "https://image1.slideserve.com/2754609/learning-vocabulary-l.jpg",
    link: "/practice/grammar",
  },
  {
    id: 3,
    title: "Làm kiểm tra",
    description: "Làm các bài kiểm tra ôn tập",
    img: "https://clipground.com/images/a-clipart-test-1.png",
    link: "/practice/exam",
  },
];

const DataWordTable = [
  {
    id: 1,
    word: "Light",
    meaning: "Ánh sáng",
    type: "noun",
    spelling: "laɪt",
    status: 1,
    date: "2023-06-30",
  },
  {
    id: 2,
    word: "Goodbye",
    meaning: "Tạm biệt",
    type: "noun",
    spelling: "ɡʊdˈbaɪ",
    status: 2,
    date: "2023-06-30",
  },
  {
    id: 3,
    word: "Hello",
    meaning: "Xin chào",
    type: "adj",
    spelling: "həˈloʊ",
    status: 2,
    date: "2023-07-01",
  },
  {
    id: 4,
    word: "Thank you",
    meaning: "Cảm ơn",
    type: "adj",
    spelling: "θæŋk juː",
    status: 2,
    date: "2023-07-02",
  },
  {
    id: 5,
    word: "Please",
    meaning: "Làm ơn",
    type: "verb",
    spelling: "pliːz",
    status: 2,
    date: "2023-07-03",
  },
  {
    id: 6,
    word: "Yes",
    meaning: "Vâng, có",
    type: "adj",
    spelling: "jes",
    status: 2,
    date: "2023-07-04",
  },
  {
    id: 7,
    word: "No",
    meaning: "Không",
    type: "adverb",
    spelling: "noʊ",
    status: 2,
    date: "2023-07-05",
  },
  {
    id: 8,
    word: "Friend",
    meaning: "Bạn bè",
    type: "noun",
    spelling: "frend",
    status: 2,
    date: "2023-07-06",
  },
  {
    id: 9,
    word: "Family",
    meaning: "Gia đình",
    type: "adverb",
    spelling: "ˈfæmɪli",
    status: 2,
    date: "2023-07-07",
  },
  {
    id: 10,
    word: "Love",
    meaning: "Yêu",
    type: "noun",
    spelling: "lʌv",
    status: 2,
    date: "2023-07-08",
  },
  {
    id: 11,
    word: "Happy",
    meaning: "Hạnh phúc",
    type: "verb",
    spelling: "ˈhæpi",
    status: 2,
    date: "2023-07-09",
  },
  {
    id: 12,
    word: "Sad",
    meaning: "Buồn",
    type: "adj",
    spelling: "sæd",
    status: 2,
    date: "2023-07-10",
  },
];

const TotalWord = DataWordTable;

const KnownWord = [
  {
    id: 1,
    word: "Light",
    meaning: "Ánh sáng",
    type: "noun",
    spelling: "laɪt",
    status: 1,
    date: "2023-06-30",
  },
  {
    id: 2,
    word: "Goodbye",
    meaning: "Tạm biệt",
    type: "noun",
    spelling: "ɡʊdˈbaɪ",
    status: 2,
    date: "2023-06-30",
  },
  {
    id: 3,
    word: "Hello",
    meaning: "Xin chào",
    type: "adj",
    spelling: "həˈloʊ",
    status: 2,
    date: "2023-07-01",
  },
  {
    id: 4,
    word: "Thank you",
    meaning: "Cảm ơn",
    type: "adj",
    spelling: "θæŋk juː",
    status: 2,
    date: "2023-07-02",
  },
  {
    id: 5,
    word: "Please",
    meaning: "Làm ơn",
    type: "verb",
    spelling: "pliːz",
    status: 2,
    date: "2023-07-03",
  },
];

const RememberWord = [
  {
    id: 5,
    word: "Please",
    meaning: "Làm ơn",
    type: "verb",
    spelling: "pliːz",
    status: 2,
    date: "2023-07-03",
  },
  {
    id: 6,
    word: "Yes",
    meaning: "Vâng, có",
    type: "adj",
    spelling: "jes",
    status: 2,
    date: "2023-07-04",
  },
  {
    id: 7,
    word: "No",
    meaning: "Không",
    type: "adverb",
    spelling: "noʊ",
    status: 2,
    date: "2023-07-05",
  },
  {
    id: 8,
    word: "Friend",
    meaning: "Bạn bè",
    type: "noun",
    spelling: "frend",
    status: 2,
    date: "2023-07-06",
  },
  {
    id: 9,
    word: "Family",
    meaning: "Gia đình",
    type: "adverb",
    spelling: "ˈfæmɪli",
    status: 2,
    date: "2023-07-07",
  },
  {
    id: 10,
    word: "Love",
    meaning: "Yêu",
    type: "noun",
    spelling: "lʌv",
    status: 2,
    date: "2023-07-08",
  },
  {
    id: 11,
    word: "Happy",
    meaning: "Hạnh phúc",
    type: "verb",
    spelling: "ˈhæpi",
    status: 2,
    date: "2023-07-09",
  },
  {
    id: 12,
    word: "Sad",
    meaning: "Buồn",
    type: "adj",
    spelling: "sæd",
    status: 2,
    date: "2023-07-10",
  },
];

export {
  DataCard,
  DataSelect,
  DataWordTable,
  TotalWord,
  KnownWord,
  RememberWord,
};
